version: '3.7'
services:
  python-conn:
    container_name: python
    build: ./python/
    command: sh -c "sleep 10s ; python 3 ./app.py"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./mysql/
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
        - MYSQL_DATABASE: 'consensus'
        - MYSQL_ROOT_PASSWORD: 'gustavo'
    ports:
      - '3306:3306'